name: cacao
description: Cacao (CORS Access-Control-Allow-Origin) Proxy
version: 0.3.3-a1
homepage: https://github.com/michaelfig/cacao
author: Michael FIG <michael+cacao@fig.org>

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dependencies:
  args: ^2.4.2
  mime: ^1.0.4
  path: ^1.9.1

dev_dependencies:
  archive: ^3.4.10
  grinder: ^0.9.4
  http: ^0.13.6
  meta: ^1.1.0
  pub_semver: ^2.1.4
  test: ^1.24.3
  yaml: ^3.1.2
