name: cacao
description: Cacao (CORS Access-Control-Allow-Origin) Proxy
version: 0.3.0
homepage: https://github.com/michaelfig/cacao
author: Michael FIG <michael+cacao@fig.org>

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dependencies:
  args: ^1.5.1
  mime: ^0.9.6+2
  #  path: ^1.4.1

dev_dependencies:
  archive: ^2.0.0
  grinder: ^0.8.0
  http: ^0.12.0
  meta: ^1.1.0
  path: ^1.6.0
  pub_semver: ^1.4.0
  test: ^1.0.0
  yaml: ^2.1.0
