name: cacao
description: Localhost Cross-Origin (CORS) Proxy
version: 1.0.0-a4
homepage: https://github.com/michaelfig/cacao
author: Michael FIG <michael+cacao@fig.org>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
